#include <stdlib.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <device_launch_parameters.h>
#include <device_functions.h>
#include <cufft.h>
#include <math.h>
#include <sstream>
#include <fstream>
#include "assert.h"